### ISSUE TITLE
Error with upstream

### ISSUE THREAD

**Issue by ValentinFunk** [debops/ansible-docker#38] opened 2017-04-13 21:59 UTC
I'm trying to install docker upstream on a few servers using the following playbook (pretty much identical to example one):
```yaml
- name: Configure Backend Servers
  hosts: backend_hosts
  become: True
  vars:
     - ferm__ansible_controllers: ['0.0.0.0/0'] # Disable ferm ssh access filter
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  pre_tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
        
  roles:
    - role: "debops.etc_services"
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ docker__etc_services__dependent_list }}'

    - role: "debops.ferm"
      ferm__dependent_rules:
        - '{{ docker__ferm__dependent_rules }}'
        
    - role: "debops.docker"
      docker__upstream: True
      tags: [ 'role::docker' ]
```

Unfortunately i run into this error: 
```
RUNNING HANDLER [debops.ferm : Restart ferm] ***********************************
changed: [staging]
changed: [production]

RUNNING HANDLER [debops.docker : Restart docker] *******************************
fatal: [staging]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recomm
ended.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status doc
ker.service' and 'journalctl -xn' for details.\n"}
fatal: [production]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' rec
ommended.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status
docker.service' and 'journalctl -xn' for details.\n"}
```

**Comment by drybjed** [comment] 2017-04-14 06:34
The role has a task, "Reload systemd daemons". When you run the role, does it have a "changed" status?

Also, in your playbook, the `vars:` variable should be a YAML dictionary, not a YAML list. Currently the variable you set there is not seen by Ansible at all.

**Comment by ValentinFunk** [comment] 2017-04-14 09:02
I have deleted the cloud instances and ran the above playbook on clean machines:
Strangely enough the task is set to "Skipped" status. Below is the relevant output from debops.etc_services and debops.docker, i have left out debops.ferm output.

When i run the playbook again after the failure, it runs through fine, however the docker daemon doesn't start. Running any docker commands results in an error (error during connect connection reset by peer). Going through the log it seems i am running into #27

If there is any way i can help debug this please let me know :)

**Ansible output from first run**
```
TASK [debops.etc_services : Make sure /etc/services.d directory exists] ********
changed: [staging]
changed: [production]

TASK [debops.etc_services : Create /etc/services.d/00_ansible] *****************
changed: [staging]
changed: [production]

TASK [debops.etc_services : Divert original /etc/services] *********************
changed: [production]
changed: [staging]

TASK [debops.etc_services : Generate list of local services if requested] ******
changed: [staging] => (item={u'comment': u'Docker REST API (plain text)', u'name': u'docker', u'port': u'2375'})
changed: [staging] => (item={u'comment': u'Docker REST API (SSL)', u'name': u'docker-s', u'port': u'2376'})
changed: [production] => (item={u'comment': u'Docker REST API (plain text)', u'name': u'docker', u'port': u'2375'})
changed: [production] => (item={u'comment': u'Docker REST API (SSL)', u'name': u'docker-s', u'port': u'2376'})

TASK [debops.etc_services : Remove list of local services if requested] ********
skipping: [staging] => (item={u'comment': u'Docker REST API (plain text)', u'name': u'docker', u'port': u'2375'})
skipping: [staging] => (item={u'comment': u'Docker REST API (SSL)', u'name': u'docker-s', u'port': u'2376'})
skipping: [production] => (item={u'comment': u'Docker REST API (plain text)', u'name': u'docker', u'port': u'2375'})
skipping: [production] => (item={u'comment': u'Docker REST API (SSL)', u'name': u'docker-s', u'port': u'2376'})

TASK [debops.etc_services : Assemble services.d] *******************************
changed: [staging]
changed: [production]

TASK [debops.etc_services : Remove diversion of /etc/services] *****************
skipping: [staging]
skipping: [production]
TASK [debops.docker : Get upstream APT GPG key] ********************************
changed: [staging]
changed: [production]

TASK [debops.docker : Configure upstream APT repository] ***********************
changed: [staging]
changed: [production]

TASK [debops.docker : Remove other version if upstream is modified] ************
ok: [staging] => (item=[u'docker.io'])
ok: [production] => (item=[u'docker.io'])

TASK [debops.docker : Remove custom systemd startup file if present] ***********
skipping: [staging]
skipping: [production]

TASK [debops.docker : Install required packages] *******************************
changed: [staging] => (item=[u'docker-engine', u'aufs-tools', u'python-pip', u'python-docker', u'python-setuptools', u'bridge-utils'])
changed: [production] => (item=[u'docker-engine', u'aufs-tools', u'python-pip', u'python-docker', u'python-setuptools', u'bridge-utils'])

TASK [debops.docker : Install ferment generator] *******************************
changed: [staging]
changed: [production]

TASK [debops.docker : Install ferment wrapper script] **************************
changed: [staging]
changed: [production]

TASK [debops.docker : Check Docker version] ************************************
ok: [staging]
ok: [production]

TASK [debops.docker : Configure Docker options] ********************************
skipping: [production]
skipping: [staging]

TASK [debops.docker : Remove Upstart docker configuration file] ****************
changed: [staging]
changed: [production]

TASK [debops.docker : Configure Docker systemd options] ************************
changed: [production]
changed: [staging]

TASK [debops.docker : Remove systemd docker configuration file] ****************
skipping: [staging]
skipping: [production]

TASK [debops.docker : Make sure that systemd directory exists] *****************
ok: [staging]
ok: [production]

TASK [debops.docker : Make sure that docker.service.d directory exists] ********
changed: [staging]
changed: [production]

TASK [debops.docker : Install Debian systemd service unit] *********************
changed: [staging]
changed: [production]

TASK [debops.docker : Configure Docker proxy] **********************************
changed: [staging]
changed: [production]

TASK [debops.docker : Remove Docker proxy configuration] ***********************
skipping: [staging]
skipping: [production]

TASK [debops.docker : Reload systemd daemons] **********************************
skipping: [staging]
skipping: [production]

TASK [debops.docker : Add specified users to 'docker' group] *******************

RUNNING HANDLER [debops.ferm : Restart ferm] ***********************************
changed: [staging]
changed: [production]

RUNNING HANDLER [debops.docker : Restart docker] *******************************
fatal: [production]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recom
mended.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status dock
er.service' and 'journalctl -xn' for details.\n"}
fatal: [staging]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommen
ded.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status docker.
service' and 'journalctl -xn' for details.\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=4    unreachable=0    failed=0
production                 : ok=35   changed=29   unreachable=0    failed=1
staging                    : ok=35   changed=29   unreachable=0    failed=1
```

**Connecting to docker daemon**
```
fatal: [production]: FAILED! => {"changed": false, "cmd": "docker info", "delta": "0:00:00.602810", "end": "2017-04-14 08:58:45.533190", "failed": true, "rc": 1
, "start": "2017-04-14 08:58:44.930380", "stderr": "error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.28/info: read unix @->/var/run/docker.sock: r
ead: connection reset by peer", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [staging]: FAILED! => {"changed": false, "cmd": "docker info", "delta": "0:00:00.611884", "end": "2017-04-14 08:58:45.493231", "failed": true, "rc": 1, "
start": "2017-04-14 08:58:44.881347", "stderr": "error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.28/info: read unix @->/var/run/docker.sock: read
: connection reset by peer", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Error from /var/log/syslog confirming docker does not start**
```
pr 14 08:58:45 staging systemd[1]: Unit docker.service entered failed state.
Apr 14 08:58:45 staging systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 14 08:58:45 staging systemd[1]: Stopping Docker Application Container Engine...
Apr 14 08:58:45 staging systemd[1]: Stopping Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Starting Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Listening on Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Starting Docker Application Container Engine...
Apr 14 08:58:45 staging dockerd[5920]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a
 flag and in the configuration file: hosts: (from flag: [fd://], from file: [fd:// ])
Apr 14 08:58:45 staging systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Apr 14 08:58:45 staging systemd[1]: Failed to start Docker Application Container Engine.
Apr 14 08:58:45 staging systemd[1]: Unit docker.service entered failed state.
Apr 14 08:58:45 staging systemd[1]: docker.service holdoff time over, scheduling restart.
Apr 14 08:58:45 staging systemd[1]: Stopping Docker Application Container Engine...
Apr 14 08:58:45 staging systemd[1]: Stopping Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Starting Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Listening on Docker Socket for the API.
Apr 14 08:58:45 staging systemd[1]: Starting Docker Application Container Engine...
Apr 14 08:58:45 staging systemd[1]: docker.service start request repeated too quickly, refusing to start.
Apr 14 08:58:45 staging systemd[1]: Failed to start Docker Application Container Engine.
Apr 14 08:58:45 staging systemd[1]: Unit docker.service entered failed state.
```

**Comment by drybjed** [comment] 2017-04-14 21:43
@Kamshak The `systemctl daemon-reload` is triggered by one of [these variables](https://github.com/debops/ansible-docker/blob/master/tasks/main.yml#L171-L176) which are registered during the role execution. The task that changed the `systemd` service file for `docker` seems to be in the "changed" state so I'm not sure why the daemon reload task did not run. You could look into that using the `debug` module.

What Ansible version do you use, was it installed from Debian/Ubuntu, from Ansible APT repository, from PyPI, from GitHub? Try using the `stable-2.2` or `stable-2.3` branch from GitHub, these seem to be most reliable these days. You can build the `.deb` package from sources by running:
```
LANG=C make local_deb
```
and install it system-wide (that's how I'm using it). You could check how the role behaves on these two releases, perhaps something changed in Ansible and role needs to be modified to account for that, but I'm not really sure what would that be.

**Comment by drybjed** [comment] 2017-09-18 20:46
I'm not sure if the issue is still present. I'm closing this thread so that it doesn't block the merge of DebOps roles into unified `git` repository, it can be revisited later if needed.

**Closed as completed by drybjed** 2017-09-18 20:46 UTC
